In [1]:
import numpy as np

# Numpy数组属性

## ndarray.ndim(返回数组的维数，等于轶)

In [2]:
a = np.arange(24)
print(a.ndim)

1


In [3]:
b = a.reshape(2,4,3)
print(b.ndim)

3


## ndarray.shape(返回数组的维度，返回一个元祖)

In [4]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [5]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


## ndarray.itemsize(以字节的形式返回每个元素的大小)

In [8]:
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [9]:
y = np.array([1,2,3,4,5], dtype=np.float64)
print(y.itemsize)

8


## ndarray.flags(返回ndarray对象的内存信息)

In [10]:
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



C_CONTIGUOUS:数组是在一个单一的C风格的连续段中
F_CONTIGUOUS:数据是在一个单一的FORTRAN风格的连续段中
OWNDATA:数组拥有它所使用的内存或从另一个对象中借用它
WRITEABLE:数组区域可以被写入，将该值设置为FALSE，则数据为只读
ALIGNED:数据和所有元素都适当的对齐到硬件上
UPDATEIFCOPY:这个数组是其他数组的一个副本，当这个数组被释放时，原数组的内容将被更新

# Numpy创建数组

## numpy.empty(shape, dtype=float, order='C')
创建一个指定形状，数据类型且未初始化的数组

In [18]:
x = np.empty([3,2], dtype=int)
print(x)

[[637476624       611]
 [        0         0]
 [   131074         0]]


## numpy.zeros
创建指定大小的数组，数组元素以0来填充

In [26]:
x = np.zeros(5)
print(x)

y = np.zeros((5,), dtype=int)
print(y)

z = np.zeros((2,2), dtype=[('x','i4'),('y','i4')])
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## numpy.ones
创建指定形状的数组，数组元素以1来填充

In [28]:
x = np.ones(5)
print(x)

x = np.ones([2,2], dtype=int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]
